language: c
sudo: false
env:
  global:
  - LUAROCKS=2.3.0
  - LUA=lua5.1
  - secure: YT2nA4uGoKKYtoezg0LeN46GkcUHI4LdOVwRJmBuzqjqZ7xQk2+tIYCnWUrcoA8nTan/Fbw1BAe1ocG7JHxXP8qpL60X03pAKP6GPgqx/ZkVpIptQnFawxiMFDQkJ2xbdVM8ikmlRBZ9b+JlEEe2OVIiB9pNR1aLf3PIjC8vLWh4lQchOHQqmG+qJ6O9ie5ObnVsBmoo4oWabrkoFeArhVqFK9JST9xKvKmL5+bhibAwHDvQQjfOkpjnhZcfoTHO6oOieJlGf1LeL6QT9E0yJzZA2LnGfxcB+STdRbPt9gUVZ+dVd3zUAANmsqG908Jzsryo+q6J6fPJv/yDvDhQmtHa25ApxxnfJIZrkZkaw25/e8jN6RcFjQCfpAHZtT4mPOxBNii5ChlBkjBXvMHzzWA+kNawZSw8O9XkAu0+x1SV+6lDFhOg+Tm9icSZx/Q1gLFWAPbWq5pHWB5YwiminZn6v7W/TxoWE2SsBUikXfjlvJPl/dMCVRDu0LBET9Q89ssO8CZ+t8eumFqFwoFw5UYVJTu4OCqCZvvvvqZZmxnusEaUMBMwjy43hxVYAcaRSWYVLz+7SFnvGdfh3w1Yrqq988WcyEo8XphdKRtMrZZSDSTsQ9kuY4cgtJOmgQxKaR3dmue9KcFypi3BwhMYhFjQmHM6422C68HIUqruCO0=
branches:
  only:
  - master
before_install:
- source .travis/setenv_lua.sh
script:
- cd gphoto.lrdevplugin
- sed -i.bak "s/CONSUMER_KEY = \"\"/CONSUMER_KEY = \""$CONSUMER_KEY"\"/" GPhotoAPI.lua
- sed -i.bak "s/CONSUMER_SECRET = \"\"/CONSUMER_SECRET = \""$CONSUMER_SECRET"\"/" GPhotoAPI.lua
- for i in *.lua; do luac -o $i $i; done
- cd ..
- zip -r /tmp/lightroom-google-photo-plugin.zip gphoto.lrdevplugin
deploy:
  provider: releases
  api_key:
    secure: jVaJcq0IU78RPUsDbpn/AQmbQ2ScoKVwiaoGxJxC03MXU1tKzb682l0c4i+8pNtAJzWdCmxTJ980Fg2qrSzUvD5hVtwADyX1OeC/Vb81FsCCrubmKOQMQQGyOk3JMxQ7vcow+1u8HU5wdq/uTgI72yO7hP71WbqvT82kMMes6nPcwK0+YJyw/C4cINt6s6134PbHr41lgf/L6i2DQ4yMkxesMffRaq+9HN2nAQyrEifs2aA4sNRR4cL0uNsKWblOtTCqL21KbZa1eaRGZUza2rDHfmyxfwaqsJGPhFv1K0z9o0pVThRug5W+u12DyGYkFnx7gc+yDet0kPPJBAD6R3TyMTCX4TBZlzrnlzmwJpRc8U/c0lW+G/AbYQ6saUxIz63CygC8yi24JOeexZZRS30X+qYYl8dGnCQiYEh+qJ0bUlaLlUj1COqDZayyDI3e0VwteIp8cekS7TfeuDaYTXTK9syoYckyn4sw8eUBwkdF/+NRJH+tJarFi2Ja++6Rx96Pz79WeHjvw/0/GwYcLctM8FGr7dHxTxHdilrCtuCxvxV+vYOYeOQDhvrY0e/e5Dzn/5MnqQVWlTfjCE0NAsMbuB3dnq3zqqz0zC1Q9frW/1J2gFHAJjeIIYHtfju2GmFgR4iJyDCH7ef5uukTG2PirYFaUTXn0LkYJMxlXyU=
  file: /tmp/lightroom-google-photo-plugin.zip
  on:
    repo: stanaka/lightroom-google-photo-plugin
notifications:
  email:
    on_success: change
    on_failure: always
